version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Python code...
      - python -m unittest tests.test_calc
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - calc.py
